### ISSUE TITLE
[v3.0.5] Completely Re-work Ubisoft Authentication Workflow

### ISSUE THREAD

**Issue by deepnimma** [TrackmaniaIndia/TMIndiaBot#302]
Ubisoft Authentication workflow is completely fucked up for some reason. Re-work it so it actually works.

**Comment by NottCurious** [comment]
We could also add these as features to py-tmio as functions and use those. Will make the codebase slightly more clean in TMIndiaBot

**Comment by deepnimma** [comment]
Should be fixed with #303 
Will re-open if still broken.
